### PR TITLE
Request for Milestone 2 approval: Tic Tac Toe Game

### PR DESCRIPTION
**Pull request by marcoshdezcam**
### Tic Tac Toe Game: 
In this stage, we added the User Interface and the basic logic of the game. 

### The Authors: 
**Adesoji and Marcos **
[Live preview:](https://repl.it/join/brikdwng-marcoshdezcam1)
In this project, we used; ### Ruby ### github/workflows 
Thank You for taking the time to review our code. 💐 Thanks!

### CODE REVIEW

**Review by adaorachi — CHANGES_REQUESTED** [review]
### Hi @marcoshdezcam and @AdesojiCodeMaster :wave: 
You did a good job on this milestone and I really commend that. Almost all the basic game flows were implemented. :+1: 
However, there are just a couple of changes to work on in order to get your project approved.

---

### STATUS: CHANGES REQUIRED :recycle: 

---

- [x] For one of the game flow implementations, your game should also inform the current_player if the selected move is invalid. Remember that this can be done with an inline statement or a `puts` statement like you have for the others.

- [x] You should also ensure a loop is implemented in your game where those actions you created in the game flow is called repeatedly at each loop. Remember that you are not expected to have a functional game. This is only to mock the game flow and show in your code that these processes/actions are thought of.

- [x] In addition to the above requirement, you should also ensure that the loop is terminated at some point. You should avoid using a definite loop such as calling a number to it, e.g - `5.times do ... end`. Loops like a `while` loop are preferable. 
Here is a [hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png) from Odin-project on why a loop is also one of the basic requirement for the game.

- [**optional**]  It is not a mandatory requirement to check your README at this milestone, so this is considered an optional requirement but will be nice if you implement it. You should consider fixing the broken image link in your README or you remove it if it is not needed. This is to ensure your README is kept decent for the time being.

---

### After implementing the mandatory changes requested above, you can request another code review.
**_Note: All requirements NOT marked with OPTIONAL are mandatory._**

---

Should you have any question, kindly reach out to me on Slack with the username **@adaorachi**

Happy Coding :relaxed: 

MaryAnn Chukwuka.

**Comment by AdesojiCodeMaster** [comment]
## This is to request the code review for our project again after implementing the corrections according to the TSE recommendations; 
### Tic Tac Toe Game: 
In this stage, we added the User Interface and the basic logic of the game. 

### The Authors: 
**Adesoji and Marcos **
[Live preview:](https://repl.it/repls/NextPersonalVirtualmachine#main.rb)
In this project, we used; 
### Ruby 
### GitHub/workflows 
Thank You for taking the time to review our code. 💐 Thanks!

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work one small change before we can merge.

Right now these are missing: 
- [x] `[REQUIRED]` game informs player if the selected move is a winning move
- [x] `[REQUIRED]` game informs player if the selected move is a draw move

Remember to add inline comments/`puts` statements to inform players.

Your project looks absolutely fantastic. Just make this small change and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Comment by marcoshdezcam** [comment]
## This is to request the code review for our project again after implementing the corrections according to the TSE recommendations; 
### Milestone 2: 
It checks for a winner only with horizontal patterns. And, it's not declaring a winner with vertical and diagonal patterns. That seems like a feature to be implemented at the logical level on Milestone 3. 

### The Authors: 
**Adesoji and Marcos **
[Live preview:](https://repl.it/join/umsisrrg-marcoshdezcam1)
In this project, we used; 
### Ruby 
### GitHub/workflows 
Thank You for taking the time to review our code! 💐

**Review by expjazz — APPROVED** [review]
## Status: Project Approved :clap: 

Great work on this project :1st_place_medal: 

And also, this pull request is the most professional I have seen... :ok_hand: 

You can go ahead on the next milestones.

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

**Pull request merged**
